### ISSUE TITLE
Comparison results of rtklib localization and factor map localization under good conditions

### ISSUE THREAD

**Issue by timuxi** [weisongwen/GraphGNSSLib#20]
Professor Wen, I cloned your code today and collected **static  gnss data under open and good environment.**

Finally, the localization results of fgo and rtklib were compared, and the conclusion was drawn that the positioning accuracy of fgo is much worse than that of rtklib. 
rtklib's data can be well stabilized around a value (with an error of centimeters), while fgo's data often experiences sudden drift (sometimes with an error of 2-3 meters).
May I ask  this conclusion is correct? Is it possible to achieve centimeter level accuracy in RTK localization using GraphgnssLib.

**Comment by timuxi** [comment]
<img width="598" alt="image" src="https://user-images.githubusercontent.com/78781986/231479351-25d992a7-f457-46e6-86a8-107215c9c59f.png">
Blue and orange lines represent the positioning results of fgo with window sizes of 1 and 100.
respectively,  green represents the positioning results of rtklib.

**Comment by weisongwen** [comment]
Hi @timuxi , thanks for the feedback, and sorry for the delay. We are too busy to maintain on-time recently, :-(. 

To your question, if you are in an open area, the RTKLIB can easily be better than this repository. This is due to the following aspect: 

- we only resolve the integer ambiguities epoch-by-epoch. However, the ambiguities can be the constant across multiple epochs in open areas without the occurence of the cycle slip. The RTKLIB can use the fixed and hold mode to easily capture this feature. 
- we did not explicitly detect the cycle slips. In short, lots of engineering tricks can be conducted based on this repositoty which is one of our future work. (in fact, we will opensource a new version recently) :-)
- please feel free to tune this repository

**Comment by weisongwen** [comment]
@XikunLiu-huskit, hi Xikun, i also keep you posted here. thanks.
