### ISSUE TITLE
Why the remaining error can still reach 7 meters in the evaluated dataset?

### ISSUE THREAD

**Issue by eastnav2015** [weisongwen/GraphGNSSLib#4]
Thank you for sharing such a great package! Since the factor graph optimization is applied, why the error can still reach more than 7 meters?

**Comment by weisongwen** [comment]
Thank you for your interest! Regarding the GNSS positioning mentioned in this framework, the remaining error can still reach more than 7 meters. The is caused by several reasons.
-  **The received GNSS measurements quality is poor due to the severe multipath and NLOS receptions**. The proposed factor graph optimization (FGO) based formulation can only help to increase the robustness of the estimator against outliers. Specifically, we recently have proposed a graduated non-convexity-based outlier detection scheme. You can refer to [Wen, Weisong, Guohao Zhang, and Li-Ta Hsu. "GNSS Outlier Mitigation Via Graduated Non-Convexity Factor Graph Optimization." arXiv preprint arXiv:2109.00667 (2021).](https://arxiv.org/ftp/arxiv/papers/2109/2109.00667.pdf).
- **Only a low-cost and commercial level GNSS receiver is applied (ublox receiver) to collect the GNSS raw measurements**. Moreover, we are recently also integrating the carrier-phase in GNSS positioning only using a single GNSS receiver. See [Bai, Xiwei, Weisong Wen, and Li-Ta Hsu. "Time-correlated Window Carrier-phase Aided GNSS Positioning Using Factor Graph Optimization for Urban Positioning." arXiv preprint arXiv:2109.00683 (2021).](https://arxiv.org/pdf/2109.00683).

Best,
Weisong,

**Comment by eastnav2015** [comment]
> Thank you for your interest! Regarding the GNSS positioning mentioned in this framework, the remaining error can still reach more than 7 meters. The is caused by several reasons.
> 
> * **The received GNSS measurements quality is poor due to the severe multipath and NLOS receptions**. The proposed factor graph optimization (FGO) based formulation can only help to increase the robustness of the estimator against outliers. Specifically, we recently have proposed a graduated non-convexity-based outlier detection scheme. You can refer to [Wen, Weisong, Guohao Zhang, and Li-Ta Hsu. "GNSS Outlier Mitigation Via Graduated Non-Convexity Factor Graph Optimization." arXiv preprint arXiv:2109.00667 (2021).](https://arxiv.org/ftp/arxiv/papers/2109/2109.00667.pdf).
> * **Only a low-cost and commercial level GNSS receiver is applied (ublox receiver) to collect the GNSS raw measurements**. Moreover, we are recently also integrating the carrier-phase in GNSS positioning only using a single GNSS receiver. See [Bai, Xiwei, Weisong Wen, and Li-Ta Hsu. "Time-correlated Window Carrier-phase Aided GNSS Positioning Using Factor Graph Optimization for Urban Positioning." arXiv preprint arXiv:2109.00683 (2021).](https://arxiv.org/pdf/2109.00683).
> 
> Best, Weisong,

Thank you for the recommendation. Any plan to test the GraphGNSSLib with high quality GNSS receiver, such as geodetic-level GNSS receiver?

**Comment by weisongwen** [comment]
Closed without further comments.
